/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fAngg.java
 *
 * Created on Nov 5, 2013, 5:28:03 AM
 */

package form;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import kelas.Anggota;

/**
 *
 * @author Advan
 */
public class fAngg extends javax.swing.JFrame {
kelas.Anggota angg;
    /** Creates new form fAngg */
    public fAngg() {
        initComponents();
        angg = new Anggota();
        tbl_an.setModel(angg.modelAnggota);
        //btnJnsKel.setSelected(null);
        angg.tampilData();
        setLocationRelativeTo(null);
        tampilId();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJnsKel = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txt_cari = new javax.swing.JTextField();
        lbl_cari_an = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_an = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lbl_id_an = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        lbl_nm_an = new javax.swing.JLabel();
        lbl_jns_kel_an = new javax.swing.JLabel();
        lbl_tgl_lhr_an = new javax.swing.JLabel();
        lbl_almt_an = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlmt = new javax.swing.JTextArea();
        opt_L = new javax.swing.JRadioButton();
        opt_P = new javax.swing.JRadioButton();
        jLahir = new com.toedter.calendar.JDateChooser();
        lbl_almt_an1 = new javax.swing.JLabel();
        txtGaji = new javax.swing.JTextField();
        lbl_almt_an2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_baru = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        lbl_bk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_cari.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_cariCaretUpdate(evt);
            }
        });
        jPanel1.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 260, -1));

        lbl_cari_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_cari_an.setForeground(new java.awt.Color(51, 0, 153));
        lbl_cari_an.setText("PENCARIAN");
        jPanel1.add(lbl_cari_an, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tbl_an.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_anMouseClicked(evt);
            }
        });
        tbl_an.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tbl_anCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tbl_an);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 370, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 390, 330));

        jPanel2.setOpaque(false);

        lbl_id_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_id_an.setForeground(new java.awt.Color(51, 0, 153));
        lbl_id_an.setText("No Anggota");

        txtNo.setEditable(false);
        txtNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoActionPerformed(evt);
            }
        });

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        lbl_nm_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_nm_an.setForeground(new java.awt.Color(51, 0, 153));
        lbl_nm_an.setText("Nama");

        lbl_jns_kel_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_jns_kel_an.setForeground(new java.awt.Color(51, 0, 153));
        lbl_jns_kel_an.setText("Jenis Kelamin");

        lbl_tgl_lhr_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_tgl_lhr_an.setForeground(new java.awt.Color(51, 0, 153));
        lbl_tgl_lhr_an.setText("Tanggal Lahir");

        lbl_almt_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_almt_an.setForeground(new java.awt.Color(51, 0, 153));
        lbl_almt_an.setText("Alamat");

        txtAlmt.setColumns(20);
        txtAlmt.setRows(5);
        txtAlmt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txtAlmt);

        btnJnsKel.add(opt_L);
        opt_L.setFont(new java.awt.Font("Tahoma", 1, 11));
        opt_L.setForeground(new java.awt.Color(51, 0, 153));
        opt_L.setText("L");
        opt_L.setContentAreaFilled(false);
        opt_L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt_LActionPerformed(evt);
            }
        });

        btnJnsKel.add(opt_P);
        opt_P.setFont(new java.awt.Font("Tahoma", 1, 11));
        opt_P.setForeground(new java.awt.Color(51, 0, 153));
        opt_P.setText("P");
        opt_P.setContentAreaFilled(false);

        lbl_almt_an1.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_almt_an1.setForeground(new java.awt.Color(51, 0, 153));
        lbl_almt_an1.setText("Gaji");

        txtGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGajiActionPerformed(evt);
            }
        });

        lbl_almt_an2.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_almt_an2.setForeground(new java.awt.Color(51, 0, 153));
        lbl_almt_an2.setText("Rp");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lbl_nm_an, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lbl_id_an)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_tgl_lhr_an)
                                .addComponent(lbl_almt_an)
                                .addComponent(lbl_almt_an1))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtGaji, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_jns_kel_an)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(lbl_almt_an2)))
                        .addGap(18, 18, 18)
                        .addComponent(opt_L)
                        .addGap(29, 29, 29)
                        .addComponent(opt_P)))
                .addGap(311, 311, 311))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id_an, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nm_an, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLahir, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lbl_tgl_lhr_an))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_jns_kel_an)
                    .addComponent(opt_L)
                    .addComponent(opt_P))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_almt_an))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_almt_an2)
                    .addComponent(txtGaji, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_almt_an1))
                .addGap(20, 20, 20))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLahir, lbl_id_an, lbl_nm_an, txtNama, txtNo});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbl_almt_an1, lbl_almt_an2, txtGaji});

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 380, 330));

        jPanel3.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(".:: FORM DATA ANGGOTA ::.");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/label.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 130));

        jPanel4.setOpaque(false);

        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kembali.png"))); // NOI18N
        btn_home.setBorder(null);
        btn_home.setContentAreaFilled(false);
        btn_home.setPreferredSize(new java.awt.Dimension(60, 60));
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpan2.png"))); // NOI18N
        btn_simpan.setBorder(null);
        btn_simpan.setContentAreaFilled(false);
        btn_simpan.setPreferredSize(new java.awt.Dimension(60, 60));
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_baru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baru.png"))); // NOI18N
        btn_baru.setBorder(null);
        btn_baru.setContentAreaFilled(false);
        btn_baru.setPreferredSize(new java.awt.Dimension(60, 60));
        btn_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baruActionPerformed(evt);
            }
        });

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        btn_update.setBorder(null);
        btn_update.setContentAreaFilled(false);
        btn_update.setPreferredSize(new java.awt.Dimension(60, 60));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hapus.png"))); // NOI18N
        btn_hapus.setBorderPainted(false);
        btn_hapus.setContentAreaFilled(false);
        btn_hapus.setPreferredSize(new java.awt.Dimension(60, 60));
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_baru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_baru, btn_hapus, btn_home, btn_simpan, btn_update});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_baru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_baru, btn_hapus, btn_home, btn_simpan, btn_update});

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 340, 70));

        lbl_bk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.jpg"))); // NOI18N
        getContentPane().add(lbl_bk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void tampilId(){
        int row = tbl_an.getRowCount();
        int col = tbl_an.getColumnCount();
        if(row==0){
            txtNo.setText("1");
        } else {
        Object[] val =new Object[col];
        for (int k = 0; k < val.length - 1; k++) {
            for (int i = 0; i < row; i++) {
                for (int j = 0; j <col; j++) {
                    val[k] = tbl_an.getValueAt(i, 0);
                    String id = val[k].toString();
                    int ambil = Integer.parseInt(id.substring(4, 5))+1;
                    txtNo.setText(String.valueOf(ambil));
                    }
            }
            }
        }
    }

    private void txtNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed

}//GEN-LAST:event_txtNamaActionPerformed

    private void opt_LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt_LActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt_LActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        dispose();
        //dashboard frm = new dashboard();
        //frm.setVisible(true);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
String jk=null;
if (opt_L.isSelected()){
    jk = "L";
}else if (opt_P.isSelected()){
    jk = "P";
}
        String tampilan="yyyy-MM-dd";
        SimpleDateFormat df = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(df.format(jLahir.getDate()));

        angg.insert(txtNo.getText(), txtNama.getText(), tanggal, jk,txtAlmt.getText(), txtGaji.getText());
        btn_baruActionPerformed(evt);
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baruActionPerformed
        // TODO add your handling code here:
        txtNama.setText("");
        jLahir.setCalendar(null);
        btnJnsKel.clearSelection();
        txtAlmt.setText("");
        txtGaji.setText("");
        angg.tampilData();
        tampilId();
}//GEN-LAST:event_btn_baruActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showConfirmDialog(null, "Yakin Akan Menghapus Data?", "HAPUS DATA", JOptionPane.YES_NO_OPTION);
        if (jawab == JOptionPane.YES_OPTION){
            angg.hapusdata(txtNo.getText());
            angg.tampilData();
            btn_baruActionPerformed(evt);
        } else if (jawab == JOptionPane.NO_OPTION){
            btn_baruActionPerformed(evt);
        }
}//GEN-LAST:event_btn_hapusActionPerformed

    private void txt_cariCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_cariCaretUpdate
        // TODO add your handling code here:
        angg.cari(txt_cari.getText());
}//GEN-LAST:event_txt_cariCaretUpdate

    private void tbl_anMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_anMouseClicked
        // TODO add your handling code here:
        int row=tbl_an.getSelectedRow();
        String Id       = tbl_an.getValueAt(row, 0).toString();
        String Nama     = tbl_an.getValueAt(row, 1).toString();
        String TglLahir = tbl_an.getValueAt(row, 2).toString();
        String Jnskel   = tbl_an.getValueAt(row, 3).toString();
        String Alamat   = tbl_an.getValueAt(row, 4).toString();
        String gaji     = tbl_an.getValueAt(row, 5).toString();


        txtNo.setText(Id);
        txtNama.setText(Nama);
        
        int iTahun = Integer.parseInt(TglLahir.substring(6,10));
        int iBulan = Integer.parseInt(TglLahir.substring(3,5))-1;
        int iTgl = Integer.parseInt(TglLahir.substring(0,2));

        Calendar cal = Calendar.getInstance();
        cal.set(iTahun,iBulan,iTgl);
        jLahir.setDate(cal.getTime());

        if (Jnskel.equalsIgnoreCase("L")){
            opt_L.setSelected(true);
        } else if (Jnskel.equalsIgnoreCase("P")){
            opt_P.setSelected(true);
        }
        txtAlmt.setText(Alamat);
        txtGaji.setText(gaji);
}//GEN-LAST:event_tbl_anMouseClicked

    private void tbl_anCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tbl_anCaretPositionChanged
        // TODO add your handling code here:
}//GEN-LAST:event_tbl_anCaretPositionChanged

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        String tampilan="yyyy-MM-dd";
        SimpleDateFormat df = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(df.format(jLahir.getDate()));
        String jk=null;

        if (opt_L.isSelected()){
            jk = "L";
        }else if (opt_P.isSelected()){
            jk = "P";
        }

        int jawab = JOptionPane.showConfirmDialog(null, "Yakin Data Akan Diperbaharui?", "PERBAHARUI DATA", JOptionPane.YES_NO_OPTION);
        if(jawab == JOptionPane.YES_OPTION){
            angg.update(txtNo.getText(), txtNama.getText(), tanggal, jk,txtAlmt.getText(), txtGaji.getText());
            angg.tampilData();
            btn_baruActionPerformed(evt);
        } else if (jawab == JOptionPane.NO_OPTION){
            btn_baruActionPerformed(evt);
        }
}//GEN-LAST:event_btn_updateActionPerformed

    private void txtGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGajiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGajiActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fAngg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnJnsKel;
    private javax.swing.JButton btn_baru;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.toedter.calendar.JDateChooser jLahir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_almt_an;
    private javax.swing.JLabel lbl_almt_an1;
    private javax.swing.JLabel lbl_almt_an2;
    private javax.swing.JLabel lbl_bk;
    private javax.swing.JLabel lbl_cari_an;
    private javax.swing.JLabel lbl_id_an;
    private javax.swing.JLabel lbl_jns_kel_an;
    private javax.swing.JLabel lbl_nm_an;
    private javax.swing.JLabel lbl_tgl_lhr_an;
    private javax.swing.JRadioButton opt_L;
    private javax.swing.JRadioButton opt_P;
    private javax.swing.JTable tbl_an;
    private javax.swing.JTextArea txtAlmt;
    private javax.swing.JTextField txtGaji;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables

}
