/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fAngg.java
 *
 * Created on Nov 5, 2013, 5:28:03 AM
 */

package form;

import java.lang.Object;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import kelas.Kriteria;

/**
 *
 * @author Advan
 */
public class fKriteria extends javax.swing.JFrame {
kelas.Kriteria kri;
    /** Creates new form fAngg */
    public fKriteria() {
        initComponents();
        kri = new Kriteria();
        tbl_kri.setModel(kri.modelKriteria);
        kri.tampilData();
        setLocationRelativeTo(null);
        //tampilId();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJnsKel = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_cari = new javax.swing.JTextField();
        lbl_cari_an = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_kri = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_proses = new javax.swing.JButton();
        btn_update1 = new javax.swing.JButton();
        lbl_bk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txt_cari.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_cariCaretUpdate(evt);
            }
        });
        jPanel1.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 260, -1));

        lbl_cari_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_cari_an.setForeground(new java.awt.Color(51, 0, 153));
        lbl_cari_an.setText("PENCARIAN");
        jPanel1.add(lbl_cari_an, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tbl_kri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_kriMouseClicked(evt);
            }
        });
        tbl_kri.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tbl_kriCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tbl_kri);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 740, 230));

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 770, 290));

        jPanel3.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(".:: FORM PROSES ::.");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/label.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(246, 246, 246)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 130));

        jPanel4.setOpaque(false);

        btn_proses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prosesdata.png"))); // NOI18N
        btn_proses.setBorder(null);
        btn_proses.setContentAreaFilled(false);
        btn_proses.setPreferredSize(new java.awt.Dimension(60, 60));
        btn_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prosesActionPerformed(evt);
            }
        });

        btn_update1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kembali.png"))); // NOI18N
        btn_update1.setBorder(null);
        btn_update1.setContentAreaFilled(false);
        btn_update1.setPreferredSize(new java.awt.Dimension(60, 60));
        btn_update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(267, Short.MAX_VALUE)
                .addComponent(btn_update1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btn_proses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(302, 302, 302))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_proses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 730, 70));

        lbl_bk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.jpg"))); // NOI18N
        getContentPane().add(lbl_bk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    private void txt_cariCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_cariCaretUpdate
        // TODO add your handling code here:
        kri.cari(txt_cari.getText());
}//GEN-LAST:event_txt_cariCaretUpdate

    private void tbl_kriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_kriMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_tbl_kriMouseClicked

    private void tbl_kriCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tbl_kriCaretPositionChanged
        // TODO add your handling code here:
}//GEN-LAST:event_tbl_kriCaretPositionChanged

    private void btn_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prosesActionPerformed
        // TODO add your handling code here:
        /* from FORUM
            int row = tbl_kri.getRowCount();
            for(int i=0; i<=row;i++){
                C.add(Math.sqrt((tabel.getValueAt(i,1) *tabel.getValueAt(i,1) ) + (tabel.getValueAt(i,2) *tabel.getValueAt(i,2) + (tabel.getValueAt(i,3) *tabel.getValueAt(i,3)));
            }
         */
        int row = tbl_kri.getRowCount();
        String status   = tbl_kri.getValueAt(row, 7).toString();
        int getusia     = Integer.parseInt(tbl_kri.getValueAt(row, 2).toString());
        int getsisa     = Integer.parseInt(tbl_kri.getValueAt(row, 4).toString());
        int getstatus   = 0;
        if (status=="Lengkap"){
            getstatus = 2;
        }else{
            getstatus = 1;
        }
        int [][] arr = new int [3][row];
        //int [][] tesarr = {{getusia1, getusia2, getusia3, getusiaN},{getsisa1, getsisa2, getsisa3, getsisaN},{getstatus1, getstatus2, getstatus3, getstatusN}};
        //cari rumus cari R
        int a1c1=0, a1c2=0, a1c3=0, a2c1=0, a2c2=0, a2c3=0, a3c1=0, a3c2=0, a3c3=0;
        double C1 = Math.sqrt((a1c1 * a1c1) + (a2c1 * a2c1) + (a3c1 * a3c1));
        double C2 = Math.sqrt((a1c2 * a1c2) + (a2c2 * a2c2) + (a3c2 * a3c2));
        double C3 = Math.sqrt((a1c3 * a1c3) + (a2c3 * a2c3) + (a3c3 * a3c3));

        //end   rumus cari R
//
        //start fungsi Y min max
        int w1=2, w2=5, w3=1;
        double y1a = a1c1 / C1 * w1;
        double y1b = a2c1 / C1 * w1;
        double y1c = a3c1 / C1 * w1;
        double y2a = a1c2 / C2 * w2;
        double y2b = a2c2 / C2 * w2;
        double y2c = a3c2 / C2 * w2;
        double y3a = a1c3 / C3 * w3;
        double y3b = a2c3 / C3 * w3;
        double y3c = a3c3 / C3 * w3;

        //variabel type
        /* 1 = benefit, 0=cost*/
        int tc1 = 1;
        int tc2 = 0;
        int tc3 = 1;

//kriteria 1 == benefit
    double y1=0, y1m=0;

    //y1
    if (y1a > y1b && y1a > y1c) {
        y1 = y1a;
    } else if (y1b > y1a && y1b > y1c) {
        y1 = y1b;
    } else if (y1c > y1a && y1c > y1b) {
        y1 = y1c;
    }
    //y1m
    if (y1a < y1b && y1a < y1c) {
        y1m = y1a;
    } else if (y1b < y1a && y1b < y1c) {
        y1m = y1b;
    } else if (y1c < y1a && y1c < y1b) {
        y1m = y1c;
    }

//kriteria 2 == cost
    double y2=0, y2m=0;
    if (y2a < y2b && y2a < y2c) {
        y2 = y2a;
    } else if (y2b < y2a && y2b < y2c) {
        y2 = y2b;
    } else if (y2c < y2a && y2c < y2b) {
        y2 = y2c;
    }

    if (y2a > y2b && y2a > y2c) {
        y2m = y2a;
    } else if (y2b > y2a && y2b > y2c) {
        y2m = y2b;
    } else if (y2c > y2a && y2c > y2b) {
        y2m = y2c;
    }

//kriteria 3 == benefit
    double y3=0, y3m=0;
    if (y3a > y3b && y3a > y3c) {
        y3 = y3a;
    } else if (y3b > y3a && y3b > y3c) {
        y3 = y3b;
    } else if (y3c > y3a && y3c > y3b) {
        y3 = y3c;
    }
    if (y3a < y3b && y3a < y3c) {
        y3m = y3a;
    } else if (y3b < y3a && y3b < y3c) {
        y3m = y3b;
    } else if (y3c < y3a && y3c < y3b) {
        y3m = y3c;
    }
//end   fungsi Y min max
//
//start fungsi D
double d1 = Math.sqrt(((y1 - y1a) * (y1 - y1a)) + ((y2 - y2a) * (y2 - y2a)) + ((y3 - y3a) * (y3 - y3a)));
double d2 = Math.sqrt(((y1 - y1b) * (y1 - y1b)) + ((y2 - y2b) * (y2 - y2b)) + ((y3 - y3b) * (y3 - y3b)));
double d3 = Math.sqrt(((y1 - y1c) * (y1 - y1c)) + ((y2 - y2c) * (y2 - y2c)) + ((y3 - y3c) * (y3 - y3c)));

double d1m = Math.sqrt(((y1m - y1a) * (y1m - y1a)) + ((y2m - y2a) * (y2m - y2a)) + ((y3m - y3a) * (y3m - y3a)));
double d2m = Math.sqrt(((y1m - y1b) * (y1m - y1b)) + ((y2m - y2b) * (y2m - y2b)) + ((y3m - y3b) * (y3m - y3b)));
double d3m = Math.sqrt(((y1m - y1c) * (y1m - y1c)) + ((y2m - y2c) * (y2m - y2c)) + ((y3m - y3c) * (y3m - y3c)));
//end   fungsi D
//
//start fungsi hasil
double hasil=0;
String alt = null;

double v1 = d1m / (d1 + d1m);
double v2 = d2m / (d2 + d2m);
double v3 = d3m / (d3 + d3m);
if (v1 > v2 && v1 > v3) {
    hasil = v1;
    alt = "Pertama";
} else if (v2 > v1 && v2 > v3) {
    hasil = v2;
    alt = "Kedua";
} else if (v3 > v1 && v3 > v2) {
    hasil = v3;
    alt = "Ketiga";
}
//end   fungsi hasil
}//GEN-LAST:event_btn_prosesActionPerformed

    private void btn_update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_update1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fKriteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnJnsKel;
    private javax.swing.JButton btn_proses;
    private javax.swing.JButton btn_update1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_bk;
    private javax.swing.JLabel lbl_cari_an;
    private javax.swing.JTable tbl_kri;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables

}
