/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fRangking.java
 *
 * Created on Jan 1, 2006, 2:56:05 AM
 */

package form;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kelas.Kembali;

/**
 *
 * @author Administrator
 */
public class fRangking extends javax.swing.JDialog {
kelas.Kembali kb;
    /** Creates new form fRangking */
    public fRangking(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        kb = new Kembali();
        tbl_Kemb.setModel(kb.modelKembali);
        kb.tampilData();
        //btn_update.setVisible(true);
        btn_simpan.setVisible(false);
        tgl_hrs_kembali.setVisible(false);
        txt_tgl_kembali.setVisible(false);
    }
    public void clear(){

    txt_id_pnjm.setText("");
        txt_id_an.setText("");
        txt_id_buku.setText("");
        txt_tgl_pinjam.setText("");
        txt_hrs_kembali.setText("");
        txt_tgl_kembali.setText("");
        txt_telat.setText("");
        txt_denda.setText("");
        jKembali.setDate(null);
        tgl_hrs_kembali.setDate(null);
        jpinjam.setDate(null);
        kb.tampilData();


    }
    /*public void hitungketerlambatan(){
try{
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat as = new SimpleDateFormat("yyyy-MM-dd");
        String strDate1 = df.format(tgl_hrus_kembali.getDate());
        String strDate2 = df.format(jKembali.getDate());
        Date Tanggal1 = df.parse(strDate1);
        Date Tanggal2 = df.parse(strDate2);
        long Hari1 = Tanggal1.getTime();
        long Hari2 = Tanggal2.getTime();
        long diff = Hari2 - Hari1;
        long Lama = diff / (24 * 60 * 60 * 1000);
        String Hasil=(Long.toString(Lama));
        txt_telat.setText(Hasil);
        //txt_tgl_kembali.setText(as.format(Tanggal2));
        }catch (Exception a){
        JOptionPane.showMessageDialog(null,"vgenkai");
        }}*/

    /*public void denda(){
    int telat = Integer.parseInt(txt_telat.getText());
    if (telat>=0){
        DecimalFormat uang = new DecimalFormat("###, ###, ###");
        int bayar= telat*1000;
        String byr = Integer.toString(bayar);
        txt_denda.setText(byr);}
        else {
        txt_denda.setText(" 0");
        }

        }*/
    /*public void clear(){

    txt_id_pnjm.setText("");
        txt_id_an.setText("");
        txt_id_buku.setText("");
        txt_hrs_kembali.setText("");

        jKembali.setDate(null);
       tgl_hrus_kembali.setDate(null);
        jKembali.setDate(null);

        txt_telat.setText("");

        txt_denda.setText("");

    }*/

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_cari = new javax.swing.JTextField();
        lbl_cari_an = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Kemb = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btn_simpan = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_id_pnjm = new javax.swing.JTextField();
        txt_id_an = new javax.swing.JTextField();
        txt_id_buku = new javax.swing.JTextField();
        txt_hrs_kembali = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_telat = new javax.swing.JTextField();
        txt_denda = new javax.swing.JTextField();
        jKembali = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        txt_tgl_pinjam = new javax.swing.JTextField();
        tgl_hrs_kembali = new com.toedter.calendar.JDateChooser();
        txt_tgl_kembali = new javax.swing.JTextField();
        jpinjam = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PENGEMBALIAN");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setOpaque(false);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/label.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel14.setForeground(new java.awt.Color(51, 0, 153));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText(".:: FORM PENGEMBALIAN BUKU ::.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(580, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(413, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(50, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 940, 130));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_cari.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_cariCaretUpdate(evt);
            }
        });
        jPanel2.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 260, -1));

        lbl_cari_an.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_cari_an.setForeground(new java.awt.Color(51, 0, 153));
        lbl_cari_an.setText("Pencarian Berdasarkan No. Id Pinjam");
        jPanel2.add(lbl_cari_an, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 30));

        tbl_Kemb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Kemb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KembMouseClicked(evt);
            }
        });
        tbl_Kemb.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tbl_KembCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tbl_Kemb);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 49, 500, 310));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 520, 380));

        jPanel5.setOpaque(false);

        btn_simpan.setBorder(null);
        btn_simpan.setBorderPainted(false);
        btn_simpan.setContentAreaFilled(false);
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel5.add(btn_simpan);

        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kembali.png"))); // NOI18N
        btn_home.setBorder(null);
        btn_home.setContentAreaFilled(false);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel5.add(btn_home);

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 250, 60));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setForeground(new java.awt.Color(50, 0, 153));
        jLabel3.setText("No Anggota");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, 84, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setForeground(new java.awt.Color(50, 0, 153));
        jLabel4.setText("Kode Buku");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setForeground(new java.awt.Color(50, 0, 153));
        jLabel5.setText("Tanggal Harus Kembali");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 169, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setForeground(new java.awt.Color(50, 0, 153));
        jLabel6.setText("Tanggal Kembali");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 207, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setForeground(new java.awt.Color(50, 0, 153));
        jLabel7.setText("ID Pinjam");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, -1, -1));

        txt_id_pnjm.setEditable(false);
        jPanel1.add(txt_id_pnjm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 11, 177, -1));

        txt_id_an.setEditable(false);
        jPanel1.add(txt_id_an, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 177, -1));

        txt_id_buku.setEditable(false);
        jPanel1.add(txt_id_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 88, 177, -1));

        txt_hrs_kembali.setEditable(false);
        jPanel1.add(txt_hrs_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 164, 180, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setForeground(new java.awt.Color(50, 0, 153));
        jLabel2.setText("Keterlambatan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 242, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel10.setForeground(new java.awt.Color(50, 0, 153));
        jLabel10.setText("Hari");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 242, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel11.setForeground(new java.awt.Color(50, 0, 153));
        jLabel11.setText("Denda");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel12.setForeground(new java.awt.Color(50, 0, 153));
        jLabel12.setText("Rp");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        txt_telat.setEditable(false);
        jPanel1.add(txt_telat, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 240, 140, -1));

        txt_denda.setEditable(false);
        jPanel1.add(txt_denda, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 278, 140, -1));

        jKembali.setDateFormatString("dd-MM-yyyy");
        jKembali.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jKembaliPropertyChange(evt);
            }
        });
        jPanel1.add(jKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 180, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel13.setForeground(new java.awt.Color(50, 10, 153));
        jLabel13.setText("Tanggal Peminjaman");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 126, -1, -1));

        txt_tgl_pinjam.setEditable(false);
        jPanel1.add(txt_tgl_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 126, 177, -1));

        tgl_hrs_kembali.setEnabled(false);
        jPanel1.add(tgl_hrs_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 63, 10));
        jPanel1.add(txt_tgl_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 20, 10));
        jPanel1.add(jpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 10, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 380, 310));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red_backMEd.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cariCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_cariCaretUpdate
kb.cari(txt_cari.getText());
//kb.tampilData();// TODO add your handling code here:
}//GEN-LAST:event_txt_cariCaretUpdate

    private void tbl_KembMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KembMouseClicked
         btn_simpan.setVisible(true);
         int row =  tbl_Kemb.getSelectedRow();
         String Id =  tbl_Kemb.getValueAt(row, 0).toString();
         String ang =  tbl_Kemb.getValueAt(row, 1).toString();
         String buku =  tbl_Kemb.getValueAt(row, 2).toString();
         String pinjam = tbl_Kemb.getValueAt(row, 3).toString();
         String hrskembali =  tbl_Kemb.getValueAt(row, 4).toString();

         Calendar Kkmbali = Calendar.getInstance();
          Calendar Pinjam = Calendar.getInstance();
         //13-01-2013

        int tahun_kmb = Integer.parseInt(hrskembali.substring(6));
       int bulan_kmb = Integer.parseInt(hrskembali.substring(4, 5))-1;
        int tanggal_kmb= Integer.parseInt(hrskembali.substring(0,2));
        int tahun_Pnj = Integer.parseInt(pinjam.substring(6));
       int bulan_Pnj = Integer.parseInt(pinjam.substring(4, 5))-1;
        int tanggal_Pnj= Integer.parseInt(pinjam.substring(0,2));

        Kkmbali.set(tahun_kmb,bulan_kmb,tanggal_kmb);
        Pinjam.set(tahun_Pnj, bulan_Pnj, tanggal_Pnj);

         tgl_hrs_kembali.setDate(Kkmbali.getTime());
         jpinjam.setDate(Pinjam.getTime());
        txt_id_pnjm.setText(Id);
        txt_id_an.setText(ang);
        txt_id_buku.setText(buku);
        txt_tgl_pinjam.setText(pinjam);
        txt_hrs_kembali.setText(hrskembali);
        kb.tampilData();
}//GEN-LAST:event_tbl_KembMouseClicked

    private void tbl_KembCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tbl_KembCaretPositionChanged
        // TODO add your handling code here:
}//GEN-LAST:event_tbl_KembCaretPositionChanged

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
     SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tkembali = String.valueOf(sdf.format(jKembali.getDate()));
            String thrskembali = String.valueOf(sdf.format(tgl_hrs_kembali.getDate()));
            String pnj =String.valueOf(sdf.format(jpinjam.getDate()));

        int jawab = JOptionPane.showConfirmDialog(null, "Konfirmasi Pengembalian?" ,"Yakin ", JOptionPane.YES_NO_OPTION);
        if(jawab == JOptionPane.YES_OPTION){
            kb.insert(txt_id_pnjm.getText(), txt_id_an.getText(), txt_id_buku.getText(),pnj,
                thrskembali, tkembali, txt_denda.getText());
                 kb.hapusdata(txt_id_pnjm.getText());

                kb.tampilData();
                JOptionPane.showMessageDialog(null, "Buku Telah kembali!!!");

                clear();
        } else {
        clear();
       
        kb.tampilData();
        btn_simpan.setVisible(true);}
        // TODO add your handling code here:
}//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        dispose();
      //dashboard frm = new dashboard();
        //frm.setVisible(true);

}//GEN-LAST:event_btn_homeActionPerformed

    private void jKembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jKembaliPropertyChange
        try {
            // TODO add your handling code here:
            if(jKembali.getDate()!=null){
            String hrskembali = txt_hrs_kembali.getText();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String strDate1 = sdf.format(tgl_hrs_kembali.getDate());
            String strDate2 = sdf.format(jKembali.getDate());
            Date Tanggal1 = sdf.parse(strDate1);
            Date Tanggal2 = sdf.parse(strDate2);
            long Hari1 = Tanggal1.getTime();
            long Hari2 = Tanggal2.getTime();
            long diff = Hari2 - Hari1;
            long Lama = diff / (24 * 60 * 60 * 1000);
            String Hasil=(Long.toString(Lama));
            txt_telat.setText(Hasil);
            txt_tgl_kembali.setText(sdf.format(Tanggal2));
            //txt_tgl_kembali.setText(as.format(Tanggal2));
            //String tKembali = String.valueOf(sdf.format(jKembali.getDate()));
            //Date harus = sdf.parse(txt_hrs_kembali.getText());
            //Date kembali = sdf.parse(tKembali);

        //long hKemb = kembali.getTime();
        //long hHarus = harus.getTime();
        //long diff = hKemb - hHarus;
        //long Lama = diff / (24 * 60 * 60 * 1000);
        //String Hasil=(Long.toString(diff));
        txt_telat.setText(Hasil);
        //int denda = Integer.parseInt(Hasil);
        //int totalDenda = denda*1000;
        //txt_denda.setText(String.valueOf(kembali.getTime()));
        int telat = Integer.parseInt(txt_telat.getText());
    if (telat>=0){
        //DecimalFormat uang = new DecimalFormat("###, ###, ###");
        int bayar= telat*1000;
        String byr = Integer.toString(bayar);
        txt_denda.setText(byr);}
        else {
        txt_denda.setText(" 0");
        }

            }
     
        }
        catch (ParseException ex) {
            Logger.getLogger(fRangking.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jKembaliPropertyChange

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                fRangking dialog = new fRangking(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_simpan;
    private com.toedter.calendar.JDateChooser jKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jpinjam;
    private javax.swing.JLabel lbl_cari_an;
    private javax.swing.JTable tbl_Kemb;
    private com.toedter.calendar.JDateChooser tgl_hrs_kembali;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_denda;
    private javax.swing.JTextField txt_hrs_kembali;
    private javax.swing.JTextField txt_id_an;
    private javax.swing.JTextField txt_id_buku;
    private javax.swing.JTextField txt_id_pnjm;
    private javax.swing.JTextField txt_telat;
    private javax.swing.JTextField txt_tgl_kembali;
    private javax.swing.JTextField txt_tgl_pinjam;
    // End of variables declaration//GEN-END:variables

}
