/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmpeminjaman.java
 *
 * Created on Jan 1, 2006, 2:55:55 AM
 */

package form;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class frmpeminjaman extends javax.swing.JDialog {
kelas.Pinjam pnjm;
    /** Creates new form frmpeminjaman */
    public frmpeminjaman(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
       
            initComponents();
            pnjm = new kelas.Pinjam();
            tbl_pnjm.setModel(pnjm.modelPinjam);
            pnjm.tampilData();
            btn_update.setVisible(false);
            btn_hapus.setVisible(false);
            btn_baru.setVisible(false);
            tampilId();
    }

     private void tampilId(){
        int row = tbl_pnjm.getRowCount();
        int col = tbl_pnjm.getColumnCount();
        if(row==0){
            txt_id_pnjm.setText("PN-1");
        } else {
        Object[] val =new Object[col];
        for (int k = 0; k < val.length - 1; k++) {
            for (int i = 0; i < row; i++) {
                for (int j = 0; j <col; j++) {
                    val[k] = tbl_pnjm.getValueAt(i, 0);
                    String id = val[k].toString();
                    int ambil = Integer.parseInt(id.substring(3, 4))+1;
                    txt_id_pnjm.setText("PN-"+String.valueOf(ambil));
                    }
            }
            }
        }
    }

void New(){
        tampilId();
        txt_id_an.setText("");
        txt_id_buku.setText("");
        jPinjam.setCalendar(null);
        txt_tgl_Hrus_Kemb.setText("");
        pnjm.tampilData();
        btn_update.setVisible(false);
        //btn_simpan.setVisible(true);
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_id_pnjm = new javax.swing.JTextField();
        txt_id_an = new javax.swing.JTextField();
        txt_id_buku = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPinjam = new com.toedter.calendar.JDateChooser();
        txt_tgl_Hrus_Kemb = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pnjm = new javax.swing.JTable();
        lbl_cari_an1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        btn_baru = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PEMINJAMAN");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setForeground(new java.awt.Color(50, 0, 153));
        jLabel3.setText("Kode Buku");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setForeground(new java.awt.Color(50, 0, 153));
        jLabel5.setText("Tanggal Peminjaman");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setForeground(new java.awt.Color(50, 0, 153));
        jLabel6.setText("Tanggal Harus Kembali");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setForeground(new java.awt.Color(50, 0, 153));
        jLabel7.setText("No Anggota");

        txt_id_pnjm.setEditable(false);
        txt_id_pnjm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_pnjmActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setForeground(new java.awt.Color(50, 0, 153));
        jLabel2.setText("ID Peminjaman");

        jPinjam.setDateFormatString("dd-MM-yyyy");
        jPinjam.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPinjamPropertyChange(evt);
            }
        });

        txt_tgl_Hrus_Kemb.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(64, 64, 64)
                        .addComponent(txt_id_pnjm, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(txt_id_an, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txt_tgl_Hrus_Kemb, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txt_id_pnjm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txt_id_an, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txt_id_buku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_tgl_Hrus_Kemb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 380, 270));

        jPanel4.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel8.setForeground(new java.awt.Color(51, 0, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(".:: FORM PEMINJAMAN BUKU::.");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/label.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 940, 130));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_cari.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_cariCaretUpdate(evt);
            }
        });
        jPanel2.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 260, -1));

        tbl_pnjm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_pnjm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pnjmMouseClicked(evt);
            }
        });
        tbl_pnjm.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tbl_pnjmCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tbl_pnjm);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 49, 500, 350));

        lbl_cari_an1.setFont(new java.awt.Font("Tahoma", 1, 12));
        lbl_cari_an1.setForeground(new java.awt.Color(51, 0, 153));
        lbl_cari_an1.setText("Pencarian Berdasarkan No. Id Pinjam");
        jPanel2.add(lbl_cari_an1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 520, 380));

        jPanel5.setOpaque(false);

        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kembali.png"))); // NOI18N
        btn_home.setBorder(null);
        btn_home.setContentAreaFilled(false);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel5.add(btn_home);

        btn_baru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baru.png"))); // NOI18N
        btn_baru.setBorder(null);
        btn_baru.setContentAreaFilled(false);
        btn_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baruActionPerformed(evt);
            }
        });
        jPanel5.add(btn_baru);

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpan2.png"))); // NOI18N
        btn_simpan.setBorder(null);
        btn_simpan.setContentAreaFilled(false);
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel5.add(btn_simpan);

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpan2.png"))); // NOI18N
        btn_update.setBorder(null);
        btn_update.setContentAreaFilled(false);
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel5.add(btn_update);

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hapus.png"))); // NOI18N
        btn_hapus.setBorder(null);
        btn_hapus.setContentAreaFilled(false);
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel5.add(btn_hapus);

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 290, 80));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/red_backMEd.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cariCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_cariCaretUpdate
        // TODO add your handling code here:
        pnjm.cari(txt_cari.getText());
        //pnjm.tampilData();
}//GEN-LAST:event_txt_cariCaretUpdate

    private void tbl_pnjmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pnjmMouseClicked
        // TODO add your handling code here:
       btn_simpan.setVisible(false);
       btn_update.setVisible(true);
       btn_baru.setVisible(true);
       btn_hapus.setVisible(true);
       

       int row=tbl_pnjm.getSelectedRow();
       String IdPinjam = tbl_pnjm.getValueAt(row, 0).toString();
       String IdAng=tbl_pnjm.getValueAt(row, 1).toString();
       String IdBuku=tbl_pnjm.getValueAt(row, 2).toString();
       String TglPinjam=tbl_pnjm.getValueAt(row, 3).toString();
            int iTahun = Integer.parseInt(TglPinjam.substring(6,10));
            int iBulan = Integer.parseInt(TglPinjam.substring(3,5))-1;
            int iTgl = Integer.parseInt(TglPinjam.substring(0,2));

            Calendar cal = Calendar.getInstance();
            cal.set(iTahun,iBulan,iTgl);

       String TglHarus=tbl_pnjm.getValueAt(row, 4).toString();

        txt_id_pnjm.setText(IdPinjam);
        txt_id_an.setText(IdAng);
        txt_id_buku.setText(IdBuku);
        jPinjam.setDate(cal.getTime());
        txt_tgl_Hrus_Kemb.setText(TglHarus);

}//GEN-LAST:event_tbl_pnjmMouseClicked

    private void tbl_pnjmCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tbl_pnjmCaretPositionChanged
        // TODO add your handling code here:
}//GEN-LAST:event_tbl_pnjmCaretPositionChanged

    private void btn_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baruActionPerformed
        // TODO add your handling code here:
        New();
        btn_simpan.setVisible(true);
}//GEN-LAST:event_btn_baruActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        try {
            // TODO add your handling code here:
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tpinjam = String.valueOf(sdf.format(jPinjam.getDate()));
            Date pinjam = sdf.parse(tpinjam);
            Calendar cal = Calendar.getInstance();
            cal.setTime(pinjam);
            cal.add(Calendar.DAY_OF_MONTH, 7);
            String tHrus = String.valueOf(sdf.format(cal.getTime()));

            pnjm.insert(txt_id_pnjm.getText(), txt_id_an.getText(), txt_id_buku.getText(), tpinjam, tHrus);
            pnjm.tampilData();
            New();
        } catch (ParseException ex) {
            Logger.getLogger(frmpeminjaman.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ada data yg belum dinput!!");
        }
}//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showConfirmDialog(null, "Yakin Data Akan Diperbaharui?", "PERBAHARUI DATA", JOptionPane.YES_NO_OPTION);
        if(jawab == JOptionPane.YES_OPTION){
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String tpinjam = String.valueOf(sdf.format(jPinjam.getDate()));
                Date pinjam = sdf.parse(tpinjam);
                Calendar cal = Calendar.getInstance();
                cal.setTime(pinjam);
                cal.add(Calendar.DAY_OF_MONTH, 7);
                String tHrus = String.valueOf(sdf.format(cal.getTime()));
                pnjm.update(txt_id_pnjm.getText(), txt_id_an.getText(), txt_id_buku.getText(), tpinjam, tHrus);
                pnjm.tampilData();
                New();
            } catch (ParseException ex) {
                Logger.getLogger(frmpeminjaman.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
        btn_baruActionPerformed(evt);
        }
}//GEN-LAST:event_btn_updateActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        dispose();
        //dashboard frm = new dashboard();
        //frm.setVisible(true);

}//GEN-LAST:event_btn_homeActionPerformed

    private void txt_id_pnjmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_pnjmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_pnjmActionPerformed

    private void jPinjamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPinjamPropertyChange
        // TODO add your handling code here:
        if(jPinjam.getDate()!=null){
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String tpinjam = String.valueOf(sdf.format(jPinjam.getDate()));
                Date pinjam = sdf.parse(tpinjam);
                Calendar cal = Calendar.getInstance();
                cal.setTime(pinjam);
                cal.add(Calendar.DAY_OF_MONTH, 7);
                String tHrus = String.valueOf(sdf.format(cal.getTime()));
                String iTahun = tHrus.substring(0,4);
                String iBulan = tHrus.substring(5,7);
                String iTgl = tHrus.substring(8,10);
                txt_tgl_Hrus_Kemb.setText(iTgl+"-"+iBulan+"-"+iTahun);



            } catch (ParseException ex) {
                Logger.getLogger(frmpeminjaman.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"wrong");
            }
        }
    }//GEN-LAST:event_jPinjamPropertyChange

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        pnjm.hapusdata(txt_id_pnjm.getText());
        btn_baru.setVisible(false);
        New();
        btn_simpan.setVisible(true);
        pnjm.tampilData();
    }//GEN-LAST:event_btn_hapusActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmpeminjaman dialog = new frmpeminjaman(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_baru;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private com.toedter.calendar.JDateChooser jPinjam;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cari_an1;
    private javax.swing.JTable tbl_pnjm;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id_an;
    private javax.swing.JTextField txt_id_buku;
    private javax.swing.JTextField txt_id_pnjm;
    private javax.swing.JTextField txt_tgl_Hrus_Kemb;
    // End of variables declaration//GEN-END:variables

}
